//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string BillCode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsRespond { get; set; }
        public int FilmId { get; set; }
        public string FilmName { get; set; }
    }
}
